#!/usr/bin/env python3
"""
KOSPI200 유니버스 정의

Yahoo Finance 티커 형식: {종목코드}.KS
총 200개 종목 (시가총액 상위 순)
"""

# KOSPI200 구성종목 200개
UNIVERSE_KOSPI200 = [
    # ── 대형주 TOP (기존 50개) ──
    {"ticker": "005930.KS", "name": "삼성전자", "market": "KR"},
    {"ticker": "000660.KS", "name": "SK하이닉스", "market": "KR"},
    {"ticker": "035420.KS", "name": "NAVER", "market": "KR"},
    {"ticker": "207940.KS", "name": "삼성바이오로직스", "market": "KR"},
    {"ticker": "005380.KS", "name": "현대차", "market": "KR"},
    {"ticker": "000270.KS", "name": "기아", "market": "KR"},
    {"ticker": "005490.KS", "name": "POSCO홀딩스", "market": "KR"},
    {"ticker": "051910.KS", "name": "LG화학", "market": "KR"},
    {"ticker": "055550.KS", "name": "신한지주", "market": "KR"},
    {"ticker": "105560.KS", "name": "KB금융", "market": "KR"},
    {"ticker": "028260.KS", "name": "삼성물산", "market": "KR"},
    {"ticker": "006400.KS", "name": "삼성SDI", "market": "KR"},
    {"ticker": "068270.KS", "name": "셀트리온", "market": "KR"},
    {"ticker": "086790.KS", "name": "하나금융지주", "market": "KR"},
    {"ticker": "003550.KS", "name": "LG", "market": "KR"},
    {"ticker": "066570.KS", "name": "LG전자", "market": "KR"},
    {"ticker": "034730.KS", "name": "SK", "market": "KR"},
    {"ticker": "012330.KS", "name": "현대모비스", "market": "KR"},
    {"ticker": "009150.KS", "name": "삼성전기", "market": "KR"},
    {"ticker": "096770.KS", "name": "SK이노베이션", "market": "KR"},
    {"ticker": "017670.KS", "name": "SK텔레콤", "market": "KR"},
    {"ticker": "030200.KS", "name": "KT", "market": "KR"},
    {"ticker": "316140.KS", "name": "우리금융지주", "market": "KR"},
    {"ticker": "032830.KS", "name": "삼성생명", "market": "KR"},
    {"ticker": "009540.KS", "name": "HD현대중공업", "market": "KR"},
    {"ticker": "042660.KS", "name": "한화오션", "market": "KR"},
    {"ticker": "012450.KS", "name": "한화에어로스페이스", "market": "KR"},
    {"ticker": "047810.KS", "name": "한국항공우주", "market": "KR"},
    {"ticker": "003670.KS", "name": "포스코퓨처엠", "market": "KR"},
    {"ticker": "010130.KS", "name": "고려아연", "market": "KR"},
    {"ticker": "004020.KS", "name": "현대제철", "market": "KR"},
    {"ticker": "000100.KS", "name": "유한양행", "market": "KR"},
    {"ticker": "128940.KS", "name": "한미약품", "market": "KR"},
    {"ticker": "035720.KS", "name": "카카오", "market": "KR"},
    {"ticker": "323410.KS", "name": "카카오뱅크", "market": "KR"},
    {"ticker": "018260.KS", "name": "삼성에스디에스", "market": "KR"},
    {"ticker": "024110.KS", "name": "IBK기업은행", "market": "KR"},
    {"ticker": "011200.KS", "name": "HMM", "market": "KR"},
    {"ticker": "015760.KS", "name": "한국전력", "market": "KR"},
    {"ticker": "003490.KS", "name": "대한항공", "market": "KR"},
    {"ticker": "036570.KS", "name": "엔씨소프트", "market": "KR"},
    {"ticker": "011170.KS", "name": "롯데케미칼", "market": "KR"},
    {"ticker": "009830.KS", "name": "한화솔루션", "market": "KR"},
    {"ticker": "047050.KS", "name": "포스코인터내셔널", "market": "KR"},
    {"ticker": "139480.KS", "name": "이마트", "market": "KR"},
    {"ticker": "032640.KS", "name": "LG유플러스", "market": "KR"},
    {"ticker": "000720.KS", "name": "현대건설", "market": "KR"},
    {"ticker": "326030.KS", "name": "SK바이오팜", "market": "KR"},
    {"ticker": "006280.KS", "name": "녹십자", "market": "KR"},
    {"ticker": "263750.KS", "name": "펄어비스", "market": "KR"},
    # ── 플랫폼/인터넷 ──
    {"ticker": "377300.KS", "name": "카카오페이", "market": "KR"},
    {"ticker": "293490.KS", "name": "카카오게임즈", "market": "KR"},
    {"ticker": "259960.KS", "name": "크래프톤", "market": "KR"},
    {"ticker": "112040.KS", "name": "위메이드", "market": "KR"},
    {"ticker": "192080.KS", "name": "더블유게임즈", "market": "KR"},
    # ── 배터리/에너지 ──
    {"ticker": "373220.KS", "name": "LG에너지솔루션", "market": "KR"},
    {"ticker": "247540.KS", "name": "에코프로비엠", "market": "KR"},
    {"ticker": "086520.KS", "name": "에코프로", "market": "KR"},
    # ── 자동차/부품 ──
    {"ticker": "307950.KS", "name": "현대오토에버", "market": "KR"},
    {"ticker": "011210.KS", "name": "현대위아", "market": "KR"},
    {"ticker": "086280.KS", "name": "현대글로비스", "market": "KR"},
    # ── 금융/보험 ──
    {"ticker": "000810.KS", "name": "삼성화재", "market": "KR"},
    {"ticker": "016360.KS", "name": "삼성증권", "market": "KR"},
    {"ticker": "006800.KS", "name": "미래에셋증권", "market": "KR"},
    {"ticker": "005940.KS", "name": "NH투자증권", "market": "KR"},
    {"ticker": "039490.KS", "name": "키움증권", "market": "KR"},
    {"ticker": "071050.KS", "name": "한국금융지주", "market": "KR"},
    {"ticker": "005830.KS", "name": "DB손해보험", "market": "KR"},
    {"ticker": "138040.KS", "name": "메리츠금융지주", "market": "KR"},
    {"ticker": "029780.KS", "name": "삼성카드", "market": "KR"},
    {"ticker": "175330.KS", "name": "JB금융지주", "market": "KR"},
    {"ticker": "138930.KS", "name": "BNK금융지주", "market": "KR"},
    {"ticker": "001450.KS", "name": "현대해상", "market": "KR"},
    {"ticker": "082640.KS", "name": "동양생명", "market": "KR"},
    {"ticker": "088350.KS", "name": "한화생명", "market": "KR"},
    {"ticker": "000370.KS", "name": "한화손해보험", "market": "KR"},
    {"ticker": "001070.KS", "name": "코리안리", "market": "KR"},
    # ── 중공업/에너지 ──
    {"ticker": "034020.KS", "name": "두산에너빌리티", "market": "KR"},
    {"ticker": "267260.KS", "name": "HD현대일렉트릭", "market": "KR"},
    {"ticker": "443060.KS", "name": "HD현대마린솔루션", "market": "KR"},
    {"ticker": "336260.KS", "name": "두산퓨얼셀", "market": "KR"},
    {"ticker": "241560.KS", "name": "두산밥캣", "market": "KR"},
    {"ticker": "267270.KS", "name": "HD현대건설기계", "market": "KR"},
    {"ticker": "017800.KS", "name": "현대엘리베이터", "market": "KR"},
    # ── 화학/소재 ──
    {"ticker": "004800.KS", "name": "효성", "market": "KR"},
    {"ticker": "298050.KS", "name": "효성첨단소재", "market": "KR"},
    {"ticker": "010060.KS", "name": "OCI홀딩스", "market": "KR"},
    {"ticker": "011780.KS", "name": "금호석유", "market": "KR"},
    {"ticker": "011790.KS", "name": "SKC", "market": "KR"},
    {"ticker": "003600.KS", "name": "SK케미칼", "market": "KR"},
    {"ticker": "004000.KS", "name": "롯데정밀화학", "market": "KR"},
    {"ticker": "002380.KS", "name": "KCC", "market": "KR"},
    {"ticker": "103140.KS", "name": "풍산", "market": "KR"},
    # ── 유통/소비재 ──
    {"ticker": "023530.KS", "name": "롯데쇼핑", "market": "KR"},
    {"ticker": "004990.KS", "name": "롯데지주", "market": "KR"},
    {"ticker": "007070.KS", "name": "GS리테일", "market": "KR"},
    {"ticker": "282330.KS", "name": "BGF리테일", "market": "KR"},
    {"ticker": "069960.KS", "name": "현대백화점", "market": "KR"},
    {"ticker": "004170.KS", "name": "신세계", "market": "KR"},
    {"ticker": "021240.KS", "name": "코웨이", "market": "KR"},
    {"ticker": "009240.KS", "name": "한샘", "market": "KR"},
    {"ticker": "192400.KS", "name": "쿠쿠홀딩스", "market": "KR"},
    {"ticker": "002790.KS", "name": "아모레G", "market": "KR"},
    {"ticker": "001740.KS", "name": "SK네트웍스", "market": "KR"},
    # ── 식품/음료 ──
    {"ticker": "097950.KS", "name": "CJ제일제당", "market": "KR"},
    {"ticker": "001040.KS", "name": "CJ", "market": "KR"},
    {"ticker": "271560.KS", "name": "오리온", "market": "KR"},
    {"ticker": "004370.KS", "name": "농심", "market": "KR"},
    {"ticker": "000080.KS", "name": "하이트진로", "market": "KR"},
    {"ticker": "000070.KS", "name": "삼양홀딩스", "market": "KR"},
    {"ticker": "033780.KS", "name": "KT&G", "market": "KR"},
    {"ticker": "007310.KS", "name": "오뚜기", "market": "KR"},
    {"ticker": "005180.KS", "name": "빙그레", "market": "KR"},
    # ── 에너지/정유 ──
    {"ticker": "010950.KS", "name": "S-Oil", "market": "KR"},
    {"ticker": "078930.KS", "name": "GS", "market": "KR"},
    {"ticker": "018670.KS", "name": "SK가스", "market": "KR"},
    {"ticker": "036460.KS", "name": "한국가스공사", "market": "KR"},
    # ── 전력/유틸리티 ──
    {"ticker": "052690.KS", "name": "한국전력기술", "market": "KR"},
    {"ticker": "051600.KS", "name": "한전KPS", "market": "KR"},
    {"ticker": "020150.KS", "name": "일진전기", "market": "KR"},
    # ── 전기/전자부품 ──
    {"ticker": "010120.KS", "name": "LS일렉트릭", "market": "KR"},
    {"ticker": "006260.KS", "name": "LS", "market": "KR"},
    {"ticker": "007810.KS", "name": "코리아써키트", "market": "KR"},
    # ── 반도체 장비/소재 ──
    {"ticker": "056190.KS", "name": "에스에프에이", "market": "KR"},
    {"ticker": "058470.KS", "name": "리노공업", "market": "KR"},
    {"ticker": "140860.KS", "name": "파크시스템스", "market": "KR"},
    {"ticker": "064760.KS", "name": "케이씨텍", "market": "KR"},
    {"ticker": "357780.KS", "name": "솔브레인", "market": "KR"},
    {"ticker": "005290.KS", "name": "동진쎄미켐", "market": "KR"},
    {"ticker": "240810.KS", "name": "원익IPS", "market": "KR"},
    {"ticker": "403870.KS", "name": "HPSP", "market": "KR"},
    {"ticker": "039030.KS", "name": "이오테크닉스", "market": "KR"},
    {"ticker": "079370.KS", "name": "제우스", "market": "KR"},
    {"ticker": "183300.KS", "name": "코미코", "market": "KR"},
    {"ticker": "042700.KS", "name": "한미반도체", "market": "KR"},
    {"ticker": "402340.KS", "name": "SK스퀘어", "market": "KR"},
    # ── 로봇/자동화 ──
    {"ticker": "277810.KS", "name": "레인보우로보틱스", "market": "KR"},
    # ── 뷰티/화장품 ──
    {"ticker": "090430.KS", "name": "아모레퍼시픽", "market": "KR"},
    {"ticker": "051900.KS", "name": "LG생활건강", "market": "KR"},
    {"ticker": "237880.KS", "name": "클리오", "market": "KR"},
    {"ticker": "161890.KS", "name": "한국콜마", "market": "KR"},
    {"ticker": "192820.KS", "name": "코스맥스", "market": "KR"},
    # ── 제약/바이오 ──
    {"ticker": "145720.KS", "name": "덴티움", "market": "KR"},
    {"ticker": "141080.KS", "name": "레고켐바이오", "market": "KR"},
    {"ticker": "195940.KS", "name": "HK이노엔", "market": "KR"},
    {"ticker": "170900.KS", "name": "동아에스티", "market": "KR"},
    {"ticker": "069620.KS", "name": "대웅제약", "market": "KR"},
    {"ticker": "185750.KS", "name": "종근당", "market": "KR"},
    {"ticker": "003850.KS", "name": "보령", "market": "KR"},
    {"ticker": "007570.KS", "name": "일양약품", "market": "KR"},
    {"ticker": "003000.KS", "name": "부광약품", "market": "KR"},
    {"ticker": "235980.KS", "name": "메드팩토", "market": "KR"},
    {"ticker": "007780.KS", "name": "셀트리온제약", "market": "KR"},
    {"ticker": "068760.KS", "name": "셀트리온헬스케어", "market": "KR"},
    {"ticker": "009420.KS", "name": "한올바이오파마", "market": "KR"},
    {"ticker": "214150.KS", "name": "클래시스", "market": "KR"},
    # ── 조선/해운 ──
    {"ticker": "010140.KS", "name": "삼성중공업", "market": "KR"},
    {"ticker": "028670.KS", "name": "팬오션", "market": "KR"},
    {"ticker": "005880.KS", "name": "대한해운", "market": "KR"},
    # ── 방산/항공 ──
    {"ticker": "000880.KS", "name": "한화", "market": "KR"},
    {"ticker": "272210.KS", "name": "한화시스템", "market": "KR"},
    {"ticker": "079550.KS", "name": "LIG넥스원", "market": "KR"},
    {"ticker": "064350.KS", "name": "현대로템", "market": "KR"},
    # ── 건설 ──
    {"ticker": "047040.KS", "name": "대우건설", "market": "KR"},
    {"ticker": "000210.KS", "name": "DL", "market": "KR"},
    # ── 타이어 ──
    {"ticker": "002350.KS", "name": "넥센타이어", "market": "KR"},
    {"ticker": "000240.KS", "name": "한국타이어앤테크놀로지", "market": "KR"},
    {"ticker": "073240.KS", "name": "금호타이어", "market": "KR"},
    # ── 기타 산업재 ──
    {"ticker": "004490.KS", "name": "세방전지", "market": "KR"},
    {"ticker": "003240.KS", "name": "태광산업", "market": "KR"},
    {"ticker": "000150.KS", "name": "두산", "market": "KR"},
    {"ticker": "016380.KS", "name": "KG스틸", "market": "KR"},
    {"ticker": "003410.KS", "name": "쌍용C&E", "market": "KR"},
    {"ticker": "004140.KS", "name": "동양", "market": "KR"},
    {"ticker": "060980.KS", "name": "한양이엔지", "market": "KR"},
    {"ticker": "025980.KS", "name": "아난티", "market": "KR"},
    # ── 추가 제약/바이오 ──
    {"ticker": "950130.KS", "name": "엑세스바이오", "market": "KR"},
    {"ticker": "214420.KS", "name": "토니모리", "market": "KR"},
    # ── 추가 IT/소프트웨어 ──
    {"ticker": "036800.KS", "name": "나이스정보통신", "market": "KR"},
    {"ticker": "053800.KS", "name": "안랩", "market": "KR"},
    {"ticker": "041510.KS", "name": "에스엠", "market": "KR"},
    {"ticker": "035900.KS", "name": "JYP엔터테인먼트", "market": "KR"},
    {"ticker": "352820.KS", "name": "하이브", "market": "KR"},
    {"ticker": "041960.KS", "name": "코미팜", "market": "KR"},
    # ── 추가 소재/화학 ──
    {"ticker": "006650.KS", "name": "대한유화", "market": "KR"},
    {"ticker": "014830.KS", "name": "유니드", "market": "KR"},
    {"ticker": "008260.KS", "name": "NI스틸", "market": "KR"},
    {"ticker": "010780.KS", "name": "아이에스동서", "market": "KR"},
    {"ticker": "001680.KS", "name": "대상", "market": "KR"},
    # ── 추가 금융 ──
    {"ticker": "085620.KS", "name": "미래에셋생명", "market": "KR"},
    {"ticker": "016610.KS", "name": "DB금융투자", "market": "KR"},
    {"ticker": "030610.KS", "name": "교보증권", "market": "KR"},
    # ── 추가 유통/서비스 ──
    {"ticker": "000670.KS", "name": "영풍", "market": "KR"},
    {"ticker": "004560.KS", "name": "현대비앤지스틸", "market": "KR"},
    {"ticker": "012630.KS", "name": "HDC", "market": "KR"},
    {"ticker": "005440.KS", "name": "현대그린푸드", "market": "KR"},
    {"ticker": "047080.KS", "name": "반도홀딩스", "market": "KR"},
    {"ticker": "011300.KS", "name": "성안", "market": "KR"},
    {"ticker": "008930.KS", "name": "한미사이언스", "market": "KR"},
    {"ticker": "024090.KS", "name": "DN오토모티브", "market": "KR"},
]
