#!/usr/bin/env python3
"""
S&P500 유니버스 정의

Yahoo Finance 티커 형식: {심볼} (suffix 없음)
총 500개 종목
"""

# S&P500 구성종목 500개
UNIVERSE_SP500 = [
    # ── 기존 99개 (S&P100 핵심 대형주) ──
    {"ticker": "AAPL", "name": "Apple", "market": "US"},
    {"ticker": "MSFT", "name": "Microsoft", "market": "US"},
    {"ticker": "NVDA", "name": "NVIDIA", "market": "US"},
    {"ticker": "AMZN", "name": "Amazon", "market": "US"},
    {"ticker": "META", "name": "Meta", "market": "US"},
    {"ticker": "GOOGL", "name": "Alphabet", "market": "US"},
    {"ticker": "TSLA", "name": "Tesla", "market": "US"},
    {"ticker": "LLY", "name": "Eli Lilly", "market": "US"},
    {"ticker": "AVGO", "name": "Broadcom", "market": "US"},
    {"ticker": "UNH", "name": "UnitedHealth", "market": "US"},
    {"ticker": "JPM", "name": "JPMorgan", "market": "US"},
    {"ticker": "XOM", "name": "Exxon Mobil", "market": "US"},
    {"ticker": "V", "name": "Visa", "market": "US"},
    {"ticker": "MA", "name": "Mastercard", "market": "US"},
    {"ticker": "PG", "name": "Procter & Gamble", "market": "US"},
    {"ticker": "HD", "name": "Home Depot", "market": "US"},
    {"ticker": "COST", "name": "Costco", "market": "US"},
    {"ticker": "MRK", "name": "Merck", "market": "US"},
    {"ticker": "ABBV", "name": "AbbVie", "market": "US"},
    {"ticker": "CVX", "name": "Chevron", "market": "US"},
    {"ticker": "PEP", "name": "PepsiCo", "market": "US"},
    {"ticker": "KO", "name": "Coca-Cola", "market": "US"},
    {"ticker": "CRM", "name": "Salesforce", "market": "US"},
    {"ticker": "TMO", "name": "Thermo Fisher", "market": "US"},
    {"ticker": "WMT", "name": "Walmart", "market": "US"},
    {"ticker": "ORCL", "name": "Oracle", "market": "US"},
    {"ticker": "BAC", "name": "Bank of America", "market": "US"},
    {"ticker": "ACN", "name": "Accenture", "market": "US"},
    {"ticker": "MCD", "name": "McDonald's", "market": "US"},
    {"ticker": "CSCO", "name": "Cisco", "market": "US"},
    {"ticker": "AMD", "name": "AMD", "market": "US"},
    {"ticker": "ABT", "name": "Abbott", "market": "US"},
    {"ticker": "NFLX", "name": "Netflix", "market": "US"},
    {"ticker": "LIN", "name": "Linde", "market": "US"},
    {"ticker": "GE", "name": "GE Aerospace", "market": "US"},
    {"ticker": "TXN", "name": "Texas Instruments", "market": "US"},
    {"ticker": "DHR", "name": "Danaher", "market": "US"},
    {"ticker": "RTX", "name": "RTX Corp", "market": "US"},
    {"ticker": "QCOM", "name": "Qualcomm", "market": "US"},
    {"ticker": "DIS", "name": "Disney", "market": "US"},
    {"ticker": "VZ", "name": "Verizon", "market": "US"},
    {"ticker": "IBM", "name": "IBM", "market": "US"},
    {"ticker": "CAT", "name": "Caterpillar", "market": "US"},
    {"ticker": "AMGN", "name": "Amgen", "market": "US"},
    {"ticker": "NOW", "name": "ServiceNow", "market": "US"},
    {"ticker": "GS", "name": "Goldman Sachs", "market": "US"},
    {"ticker": "INTU", "name": "Intuit", "market": "US"},
    {"ticker": "SPGI", "name": "S&P Global", "market": "US"},
    {"ticker": "UPS", "name": "UPS", "market": "US"},
    {"ticker": "BA", "name": "Boeing", "market": "US"},
    {"ticker": "HON", "name": "Honeywell", "market": "US"},
    {"ticker": "SYK", "name": "Stryker", "market": "US"},
    {"ticker": "BKNG", "name": "Booking Holdings", "market": "US"},
    {"ticker": "AXP", "name": "American Express", "market": "US"},
    {"ticker": "BLK", "name": "BlackRock", "market": "US"},
    {"ticker": "GILD", "name": "Gilead", "market": "US"},
    {"ticker": "DE", "name": "Deere & Company", "market": "US"},
    {"ticker": "ISRG", "name": "Intuitive Surgical", "market": "US"},
    {"ticker": "ADI", "name": "Analog Devices", "market": "US"},
    {"ticker": "T", "name": "AT&T", "market": "US"},
    {"ticker": "NEE", "name": "NextEra Energy", "market": "US"},
    {"ticker": "PM", "name": "Philip Morris", "market": "US"},
    {"ticker": "LOW", "name": "Lowe's", "market": "US"},
    {"ticker": "SCHW", "name": "Charles Schwab", "market": "US"},
    {"ticker": "MS", "name": "Morgan Stanley", "market": "US"},
    {"ticker": "CB", "name": "Chubb", "market": "US"},
    {"ticker": "TJX", "name": "TJX Companies", "market": "US"},
    {"ticker": "ADP", "name": "ADP", "market": "US"},
    {"ticker": "AON", "name": "Aon", "market": "US"},
    {"ticker": "ZTS", "name": "Zoetis", "market": "US"},
    {"ticker": "REGN", "name": "Regeneron", "market": "US"},
    {"ticker": "VRTX", "name": "Vertex Pharma", "market": "US"},
    {"ticker": "EOG", "name": "EOG Resources", "market": "US"},
    {"ticker": "SLB", "name": "SLB", "market": "US"},
    {"ticker": "MO", "name": "Altria", "market": "US"},
    {"ticker": "USB", "name": "U.S. Bancorp", "market": "US"},
    {"ticker": "PNC", "name": "PNC Financial", "market": "US"},
    {"ticker": "SO", "name": "Southern Company", "market": "US"},
    {"ticker": "DUK", "name": "Duke Energy", "market": "US"},
    {"ticker": "BSX", "name": "Boston Scientific", "market": "US"},
    {"ticker": "ICE", "name": "Intercontinental Exchange", "market": "US"},
    {"ticker": "COP", "name": "ConocoPhillips", "market": "US"},
    {"ticker": "ETN", "name": "Eaton", "market": "US"},
    {"ticker": "F", "name": "Ford", "market": "US"},
    {"ticker": "GM", "name": "General Motors", "market": "US"},
    {"ticker": "PYPL", "name": "PayPal", "market": "US"},
    {"ticker": "UBER", "name": "Uber", "market": "US"},
    {"ticker": "LMT", "name": "Lockheed Martin", "market": "US"},
    {"ticker": "NOC", "name": "Northrop Grumman", "market": "US"},
    {"ticker": "GD", "name": "General Dynamics", "market": "US"},
    {"ticker": "HCA", "name": "HCA Healthcare", "market": "US"},
    {"ticker": "PANW", "name": "Palo Alto Networks", "market": "US"},
    {"ticker": "LRCX", "name": "Lam Research", "market": "US"},
    {"ticker": "KLAC", "name": "KLA Corp", "market": "US"},
    {"ticker": "AMAT", "name": "Applied Materials", "market": "US"},
    {"ticker": "MU", "name": "Micron Technology", "market": "US"},
    {"ticker": "INTC", "name": "Intel", "market": "US"},
    {"ticker": "ADBE", "name": "Adobe", "market": "US"},
    {"ticker": "PLTR", "name": "Palantir", "market": "US"},
    # ── 기술/소프트웨어 ──
    {"ticker": "CDNS", "name": "Cadence Design", "market": "US"},
    {"ticker": "SNPS", "name": "Synopsys", "market": "US"},
    {"ticker": "MCHP", "name": "Microchip Technology", "market": "US"},
    {"ticker": "ON", "name": "ON Semiconductor", "market": "US"},
    {"ticker": "TER", "name": "Teradyne", "market": "US"},
    {"ticker": "MPWR", "name": "Monolithic Power", "market": "US"},
    {"ticker": "SWKS", "name": "Skyworks Solutions", "market": "US"},
    {"ticker": "QRVO", "name": "Qorvo", "market": "US"},
    {"ticker": "NXPI", "name": "NXP Semiconductors", "market": "US"},
    {"ticker": "STX", "name": "Seagate Technology", "market": "US"},
    {"ticker": "WDC", "name": "Western Digital", "market": "US"},
    {"ticker": "NTAP", "name": "NetApp", "market": "US"},
    {"ticker": "HPE", "name": "HP Enterprise", "market": "US"},
    {"ticker": "HPQ", "name": "HP Inc", "market": "US"},
    {"ticker": "KEYS", "name": "Keysight Technologies", "market": "US"},
    {"ticker": "ANSS", "name": "Ansys", "market": "US"},
    {"ticker": "PTC", "name": "PTC Inc", "market": "US"},
    {"ticker": "ROP", "name": "Roper Technologies", "market": "US"},
    {"ticker": "EPAM", "name": "EPAM Systems", "market": "US"},
    {"ticker": "CTSH", "name": "Cognizant", "market": "US"},
    {"ticker": "LDOS", "name": "Leidos", "market": "US"},
    {"ticker": "SAIC", "name": "SAIC", "market": "US"},
    {"ticker": "CACI", "name": "CACI International", "market": "US"},
    {"ticker": "JNPR", "name": "Juniper Networks", "market": "US"},
    {"ticker": "MSI", "name": "Motorola Solutions", "market": "US"},
    {"ticker": "ZBRA", "name": "Zebra Technologies", "market": "US"},
    {"ticker": "TTWO", "name": "Take-Two Interactive", "market": "US"},
    {"ticker": "EA", "name": "Electronic Arts", "market": "US"},
    {"ticker": "RBLX", "name": "Roblox", "market": "US"},
    {"ticker": "DDOG", "name": "Datadog", "market": "US"},
    {"ticker": "SNOW", "name": "Snowflake", "market": "US"},
    {"ticker": "NET", "name": "Cloudflare", "market": "US"},
    {"ticker": "ZS", "name": "Zscaler", "market": "US"},
    {"ticker": "CRWD", "name": "CrowdStrike", "market": "US"},
    {"ticker": "OKTA", "name": "Okta", "market": "US"},
    {"ticker": "HUBS", "name": "HubSpot", "market": "US"},
    {"ticker": "WDAY", "name": "Workday", "market": "US"},
    {"ticker": "VEEV", "name": "Veeva Systems", "market": "US"},
    {"ticker": "TEAM", "name": "Atlassian", "market": "US"},
    {"ticker": "MDB", "name": "MongoDB", "market": "US"},
    {"ticker": "FTNT", "name": "Fortinet", "market": "US"},
    {"ticker": "SPLK", "name": "Splunk", "market": "US"},
    {"ticker": "APP", "name": "AppLovin", "market": "US"},
    {"ticker": "ADSK", "name": "Autodesk", "market": "US"},
    {"ticker": "ENPH", "name": "Enphase Energy", "market": "US"},
    # ── 헬스케어 ──
    {"ticker": "JNJ", "name": "Johnson & Johnson", "market": "US"},
    {"ticker": "PFE", "name": "Pfizer", "market": "US"},
    {"ticker": "BMY", "name": "Bristol-Myers Squibb", "market": "US"},
    {"ticker": "CI", "name": "Cigna", "market": "US"},
    {"ticker": "HUM", "name": "Humana", "market": "US"},
    {"ticker": "CVS", "name": "CVS Health", "market": "US"},
    {"ticker": "MCK", "name": "McKesson", "market": "US"},
    {"ticker": "ABC", "name": "AmerisourceBergen", "market": "US"},
    {"ticker": "CAH", "name": "Cardinal Health", "market": "US"},
    {"ticker": "DGX", "name": "Quest Diagnostics", "market": "US"},
    {"ticker": "LH", "name": "Labcorp", "market": "US"},
    {"ticker": "IQV", "name": "IQVIA Holdings", "market": "US"},
    {"ticker": "ZBH", "name": "Zimmer Biomet", "market": "US"},
    {"ticker": "BAX", "name": "Baxter International", "market": "US"},
    {"ticker": "BDX", "name": "Becton Dickinson", "market": "US"},
    {"ticker": "EW", "name": "Edwards Lifesciences", "market": "US"},
    {"ticker": "XRAY", "name": "Dentsply Sirona", "market": "US"},
    {"ticker": "RVTY", "name": "Revvity", "market": "US"},
    {"ticker": "HOLX", "name": "Hologic", "market": "US"},
    {"ticker": "ALGN", "name": "Align Technology", "market": "US"},
    {"ticker": "MTD", "name": "Mettler-Toledo", "market": "US"},
    {"ticker": "WAT", "name": "Waters Corp", "market": "US"},
    {"ticker": "IDXX", "name": "IDEXX Laboratories", "market": "US"},
    {"ticker": "BIIB", "name": "Biogen", "market": "US"},
    {"ticker": "MRNA", "name": "Moderna", "market": "US"},
    {"ticker": "EXAS", "name": "Exact Sciences", "market": "US"},
    {"ticker": "ALNY", "name": "Alnylam Pharma", "market": "US"},
    {"ticker": "BMRN", "name": "BioMarin Pharma", "market": "US"},
    {"ticker": "SRPT", "name": "Sarepta Therapeutics", "market": "US"},
    {"ticker": "PODD", "name": "Insulet Corp", "market": "US"},
    {"ticker": "DXCM", "name": "DexCom", "market": "US"},
    {"ticker": "GEHC", "name": "GE HealthCare", "market": "US"},
    {"ticker": "RMD", "name": "ResMed", "market": "US"},
    {"ticker": "MOH", "name": "Molina Healthcare", "market": "US"},
    {"ticker": "CNC", "name": "Centene", "market": "US"},
    {"ticker": "ANTM", "name": "Elevance Health", "market": "US"},
    # ── 금융 ──
    {"ticker": "WFC", "name": "Wells Fargo", "market": "US"},
    {"ticker": "C", "name": "Citigroup", "market": "US"},
    {"ticker": "BK", "name": "Bank of New York Mellon", "market": "US"},
    {"ticker": "STT", "name": "State Street", "market": "US"},
    {"ticker": "FITB", "name": "Fifth Third Bancorp", "market": "US"},
    {"ticker": "HBAN", "name": "Huntington Bancshares", "market": "US"},
    {"ticker": "KEY", "name": "KeyCorp", "market": "US"},
    {"ticker": "RF", "name": "Regions Financial", "market": "US"},
    {"ticker": "CFG", "name": "Citizens Financial", "market": "US"},
    {"ticker": "MTB", "name": "M&T Bank", "market": "US"},
    {"ticker": "TFC", "name": "Truist Financial", "market": "US"},
    {"ticker": "COF", "name": "Capital One", "market": "US"},
    {"ticker": "DFS", "name": "Discover Financial", "market": "US"},
    {"ticker": "SYF", "name": "Synchrony Financial", "market": "US"},
    {"ticker": "ALLY", "name": "Ally Financial", "market": "US"},
    {"ticker": "WRB", "name": "W.R. Berkley", "market": "US"},
    {"ticker": "HIG", "name": "Hartford Financial", "market": "US"},
    {"ticker": "MET", "name": "MetLife", "market": "US"},
    {"ticker": "PRU", "name": "Prudential Financial", "market": "US"},
    {"ticker": "UNM", "name": "Unum Group", "market": "US"},
    {"ticker": "AFG", "name": "American Financial Group", "market": "US"},
    {"ticker": "CINF", "name": "Cincinnati Financial", "market": "US"},
    {"ticker": "FAF", "name": "First American Financial", "market": "US"},
    {"ticker": "FNF", "name": "Fidelity National Financial", "market": "US"},
    {"ticker": "MMC", "name": "Marsh McLennan", "market": "US"},
    {"ticker": "WTW", "name": "Willis Towers Watson", "market": "US"},
    {"ticker": "ACGL", "name": "Arch Capital Group", "market": "US"},
    {"ticker": "RNR", "name": "RenaissanceRe", "market": "US"},
    {"ticker": "ERIE", "name": "Erie Indemnity", "market": "US"},
    {"ticker": "ORI", "name": "Old Republic International", "market": "US"},
    {"ticker": "TRUP", "name": "Trupanion", "market": "US"},
    {"ticker": "MKTX", "name": "MarketAxess", "market": "US"},
    {"ticker": "NDAQ", "name": "Nasdaq Inc", "market": "US"},
    {"ticker": "CME", "name": "CME Group", "market": "US"},
    {"ticker": "CBOE", "name": "Cboe Global Markets", "market": "US"},
    # ── 에너지 ──
    {"ticker": "OXY", "name": "Occidental Petroleum", "market": "US"},
    {"ticker": "DVN", "name": "Devon Energy", "market": "US"},
    {"ticker": "MRO", "name": "Marathon Oil", "market": "US"},
    {"ticker": "HAL", "name": "Halliburton", "market": "US"},
    {"ticker": "BKR", "name": "Baker Hughes", "market": "US"},
    {"ticker": "FTI", "name": "TechnipFMC", "market": "US"},
    {"ticker": "PSX", "name": "Phillips 66", "market": "US"},
    {"ticker": "VLO", "name": "Valero Energy", "market": "US"},
    {"ticker": "MPC", "name": "Marathon Petroleum", "market": "US"},
    {"ticker": "HES", "name": "Hess Corp", "market": "US"},
    {"ticker": "APA", "name": "APA Corp", "market": "US"},
    {"ticker": "FANG", "name": "Diamondback Energy", "market": "US"},
    {"ticker": "CTRA", "name": "Coterra Energy", "market": "US"},
    {"ticker": "EQT", "name": "EQT Corp", "market": "US"},
    {"ticker": "AR", "name": "Antero Resources", "market": "US"},
    {"ticker": "CNX", "name": "CNX Resources", "market": "US"},
    {"ticker": "RRC", "name": "Range Resources", "market": "US"},
    {"ticker": "AES", "name": "AES Corp", "market": "US"},
    {"ticker": "NRG", "name": "NRG Energy", "market": "US"},
    {"ticker": "EXC", "name": "Exelon", "market": "US"},
    {"ticker": "OGE", "name": "OGE Energy", "market": "US"},
    {"ticker": "PNW", "name": "Pinnacle West Capital", "market": "US"},
    {"ticker": "NI", "name": "NiSource", "market": "US"},
    {"ticker": "ATO", "name": "Atmos Energy", "market": "US"},
    {"ticker": "LNT", "name": "Alliant Energy", "market": "US"},
    {"ticker": "WEC", "name": "WEC Energy Group", "market": "US"},
    {"ticker": "CMS", "name": "CMS Energy", "market": "US"},
    # ── 소비재/유통 ──
    {"ticker": "TGT", "name": "Target", "market": "US"},
    {"ticker": "DG", "name": "Dollar General", "market": "US"},
    {"ticker": "DLTR", "name": "Dollar Tree", "market": "US"},
    {"ticker": "ROST", "name": "Ross Stores", "market": "US"},
    {"ticker": "BBY", "name": "Best Buy", "market": "US"},
    {"ticker": "KR", "name": "Kroger", "market": "US"},
    {"ticker": "SYY", "name": "Sysco", "market": "US"},
    {"ticker": "USFD", "name": "US Foods", "market": "US"},
    {"ticker": "NKE", "name": "Nike", "market": "US"},
    {"ticker": "VFC", "name": "VF Corp", "market": "US"},
    {"ticker": "PVH", "name": "PVH Corp", "market": "US"},
    {"ticker": "RL", "name": "Ralph Lauren", "market": "US"},
    {"ticker": "TPR", "name": "Tapestry", "market": "US"},
    {"ticker": "CPRI", "name": "Capri Holdings", "market": "US"},
    {"ticker": "SKX", "name": "Skechers", "market": "US"},
    {"ticker": "LEVI", "name": "Levi Strauss", "market": "US"},
    {"ticker": "DECK", "name": "Deckers Outdoor", "market": "US"},
    {"ticker": "HELE", "name": "Helen of Troy", "market": "US"},
    {"ticker": "CHD", "name": "Church & Dwight", "market": "US"},
    {"ticker": "CLX", "name": "Clorox", "market": "US"},
    {"ticker": "CL", "name": "Colgate-Palmolive", "market": "US"},
    {"ticker": "ENR", "name": "Energizer Holdings", "market": "US"},
    {"ticker": "KMB", "name": "Kimberly-Clark", "market": "US"},
    {"ticker": "EL", "name": "Estee Lauder", "market": "US"},
    {"ticker": "SJM", "name": "J.M. Smucker", "market": "US"},
    {"ticker": "CAG", "name": "Conagra Brands", "market": "US"},
    {"ticker": "GIS", "name": "General Mills", "market": "US"},
    {"ticker": "HSY", "name": "Hershey", "market": "US"},
    {"ticker": "MKC", "name": "McCormick", "market": "US"},
    {"ticker": "CPB", "name": "Campbell Soup", "market": "US"},
    {"ticker": "K", "name": "Kellanova", "market": "US"},
    {"ticker": "HRL", "name": "Hormel Foods", "market": "US"},
    {"ticker": "TSN", "name": "Tyson Foods", "market": "US"},
    {"ticker": "LW", "name": "Lamb Weston", "market": "US"},
    # ── 여행/레저/호텔 ──
    {"ticker": "HLT", "name": "Hilton Worldwide", "market": "US"},
    {"ticker": "MAR", "name": "Marriott International", "market": "US"},
    {"ticker": "H", "name": "Hyatt Hotels", "market": "US"},
    {"ticker": "WH", "name": "Wyndham Hotels", "market": "US"},
    {"ticker": "RHP", "name": "Ryman Hospitality", "market": "US"},
    {"ticker": "CCL", "name": "Carnival Corp", "market": "US"},
    {"ticker": "RCL", "name": "Royal Caribbean", "market": "US"},
    {"ticker": "NCLH", "name": "Norwegian Cruise Line", "market": "US"},
    {"ticker": "LYV", "name": "Live Nation", "market": "US"},
    # ── 산업재 ──
    {"ticker": "MMM", "name": "3M", "market": "US"},
    {"ticker": "EMR", "name": "Emerson Electric", "market": "US"},
    {"ticker": "ITW", "name": "Illinois Tool Works", "market": "US"},
    {"ticker": "DOV", "name": "Dover Corp", "market": "US"},
    {"ticker": "ROK", "name": "Rockwell Automation", "market": "US"},
    {"ticker": "AME", "name": "AMETEK", "market": "US"},
    {"ticker": "PH", "name": "Parker Hannifin", "market": "US"},
    {"ticker": "XPO", "name": "XPO Inc", "market": "US"},
    {"ticker": "CHRW", "name": "C.H. Robinson", "market": "US"},
    {"ticker": "ODFL", "name": "Old Dominion Freight", "market": "US"},
    {"ticker": "JBHT", "name": "J.B. Hunt Transport", "market": "US"},
    {"ticker": "KNX", "name": "Knight-Swift Transport", "market": "US"},
    {"ticker": "R", "name": "Ryder System", "market": "US"},
    {"ticker": "URI", "name": "United Rentals", "market": "US"},
    {"ticker": "GWW", "name": "W.W. Grainger", "market": "US"},
    {"ticker": "FAST", "name": "Fastenal", "market": "US"},
    {"ticker": "MSC", "name": "MSC Industrial", "market": "US"},
    {"ticker": "WDFC", "name": "WD-40 Company", "market": "US"},
    {"ticker": "HXL", "name": "Hexcel Corp", "market": "US"},
    {"ticker": "AWI", "name": "Armstrong World Industries", "market": "US"},
    {"ticker": "MHK", "name": "Mohawk Industries", "market": "US"},
    {"ticker": "MAS", "name": "Masco Corp", "market": "US"},
    {"ticker": "SWK", "name": "Stanley Black & Decker", "market": "US"},
    {"ticker": "SNA", "name": "Snap-on", "market": "US"},
    {"ticker": "KMT", "name": "Kennametal", "market": "US"},
    {"ticker": "GNRC", "name": "Generac Holdings", "market": "US"},
    {"ticker": "HUBB", "name": "Hubbell", "market": "US"},
    {"ticker": "AOS", "name": "A.O. Smith", "market": "US"},
    {"ticker": "FLS", "name": "Flowserve", "market": "US"},
    {"ticker": "XYL", "name": "Xylem", "market": "US"},
    {"ticker": "CARR", "name": "Carrier Global", "market": "US"},
    {"ticker": "OTIS", "name": "Otis Worldwide", "market": "US"},
    {"ticker": "TT", "name": "Trane Technologies", "market": "US"},
    {"ticker": "IR", "name": "Ingersoll Rand", "market": "US"},
    {"ticker": "PWR", "name": "Quanta Services", "market": "US"},
    {"ticker": "MTZ", "name": "MasTec", "market": "US"},
    # ── 통신/미디어 ──
    {"ticker": "TMUS", "name": "T-Mobile US", "market": "US"},
    {"ticker": "LUMN", "name": "Lumen Technologies", "market": "US"},
    {"ticker": "WBD", "name": "Warner Bros Discovery", "market": "US"},
    {"ticker": "FOX", "name": "Fox Corp", "market": "US"},
    {"ticker": "FOXA", "name": "Fox Corp Class A", "market": "US"},
    {"ticker": "NWS", "name": "News Corp", "market": "US"},
    {"ticker": "OMC", "name": "Omnicom Group", "market": "US"},
    {"ticker": "IPG", "name": "Interpublic Group", "market": "US"},
    {"ticker": "NYT", "name": "New York Times", "market": "US"},
    {"ticker": "CABO", "name": "Cable One", "market": "US"},
    {"ticker": "CHTR", "name": "Charter Communications", "market": "US"},
    {"ticker": "CMCSA", "name": "Comcast", "market": "US"},
    {"ticker": "PARA", "name": "Paramount Global", "market": "US"},
    {"ticker": "SIRI", "name": "Sirius XM Holdings", "market": "US"},
    # ── 부동산/리츠 ──
    {"ticker": "AMT", "name": "American Tower", "market": "US"},
    {"ticker": "CCI", "name": "Crown Castle", "market": "US"},
    {"ticker": "EQIX", "name": "Equinix", "market": "US"},
    {"ticker": "PLD", "name": "Prologis", "market": "US"},
    {"ticker": "PSA", "name": "Public Storage", "market": "US"},
    {"ticker": "EXR", "name": "Extra Space Storage", "market": "US"},
    {"ticker": "AVB", "name": "AvalonBay Communities", "market": "US"},
    {"ticker": "EQR", "name": "Equity Residential", "market": "US"},
    {"ticker": "ESS", "name": "Essex Property Trust", "market": "US"},
    {"ticker": "MAA", "name": "Mid-America Apartment", "market": "US"},
    {"ticker": "UDR", "name": "UDR Inc", "market": "US"},
    {"ticker": "CPT", "name": "Camden Property Trust", "market": "US"},
    {"ticker": "NNN", "name": "NNN REIT", "market": "US"},
    {"ticker": "O", "name": "Realty Income", "market": "US"},
    {"ticker": "WPC", "name": "W.P. Carey", "market": "US"},
    {"ticker": "ADC", "name": "Agree Realty", "market": "US"},
    {"ticker": "EPRT", "name": "Essential Properties Realty", "market": "US"},
    {"ticker": "VICI", "name": "VICI Properties", "market": "US"},
    {"ticker": "GLPI", "name": "Gaming & Leisure Properties", "market": "US"},
    {"ticker": "BXP", "name": "BXP Inc", "market": "US"},
    {"ticker": "VNO", "name": "Vornado Realty", "market": "US"},
    {"ticker": "SLG", "name": "SL Green Realty", "market": "US"},
    {"ticker": "KIM", "name": "Kimco Realty", "market": "US"},
    {"ticker": "FRT", "name": "Federal Realty", "market": "US"},
    {"ticker": "REG", "name": "Regency Centers", "market": "US"},
    {"ticker": "BRX", "name": "Brixmor Property Group", "market": "US"},
    {"ticker": "ARE", "name": "Alexandria Real Estate", "market": "US"},
    {"ticker": "OHI", "name": "Omega Healthcare", "market": "US"},
    {"ticker": "WELL", "name": "Welltower", "market": "US"},
    {"ticker": "VTR", "name": "Ventas", "market": "US"},
    {"ticker": "DOC", "name": "Healthpeak Properties", "market": "US"},
    {"ticker": "NHI", "name": "National Health Investors", "market": "US"},
    {"ticker": "LTC", "name": "LTC Properties", "market": "US"},
    # ── 유틸리티 ──
    {"ticker": "AWK", "name": "American Water Works", "market": "US"},
    {"ticker": "SRE", "name": "Sempra", "market": "US"},
    {"ticker": "PCG", "name": "PG&E Corp", "market": "US"},
    {"ticker": "EIX", "name": "Edison International", "market": "US"},
    {"ticker": "PPL", "name": "PPL Corp", "market": "US"},
    {"ticker": "ETR", "name": "Entergy", "market": "US"},
    {"ticker": "EVRG", "name": "Evergy", "market": "US"},
    {"ticker": "IDA", "name": "IDACORP", "market": "US"},
    {"ticker": "POR", "name": "Portland General Electric", "market": "US"},
    {"ticker": "AVA", "name": "Avista Corp", "market": "US"},
    {"ticker": "NWE", "name": "NorthWestern Energy", "market": "US"},
    {"ticker": "OTTR", "name": "Otter Tail Corp", "market": "US"},
    {"ticker": "BKH", "name": "Black Hills Corp", "market": "US"},
    {"ticker": "UGI", "name": "UGI Corp", "market": "US"},
    # ── 소재/화학 ──
    {"ticker": "APD", "name": "Air Products", "market": "US"},
    {"ticker": "ECL", "name": "Ecolab", "market": "US"},
    {"ticker": "PPG", "name": "PPG Industries", "market": "US"},
    {"ticker": "SHW", "name": "Sherwin-Williams", "market": "US"},
    {"ticker": "FCX", "name": "Freeport-McMoRan", "market": "US"},
    {"ticker": "NEM", "name": "Newmont", "market": "US"},
    {"ticker": "AA", "name": "Alcoa", "market": "US"},
    {"ticker": "NUE", "name": "Nucor", "market": "US"},
    {"ticker": "STLD", "name": "Steel Dynamics", "market": "US"},
    {"ticker": "CF", "name": "CF Industries", "market": "US"},
    {"ticker": "MOS", "name": "Mosaic", "market": "US"},
    {"ticker": "ALB", "name": "Albemarle", "market": "US"},
    {"ticker": "LYB", "name": "LyondellBasell", "market": "US"},
    {"ticker": "DOW", "name": "Dow Inc", "market": "US"},
    {"ticker": "DD", "name": "DuPont", "market": "US"},
    {"ticker": "EMN", "name": "Eastman Chemical", "market": "US"},
    {"ticker": "CE", "name": "Celanese", "market": "US"},
    {"ticker": "IP", "name": "International Paper", "market": "US"},
    {"ticker": "PKG", "name": "Packaging Corp of America", "market": "US"},
    {"ticker": "AVY", "name": "Avery Dennison", "market": "US"},
    {"ticker": "SEE", "name": "Sealed Air", "market": "US"},
    {"ticker": "AMCR", "name": "Amcor", "market": "US"},
    # ── 항공/운송 ──
    {"ticker": "DAL", "name": "Delta Air Lines", "market": "US"},
    {"ticker": "UAL", "name": "United Airlines", "market": "US"},
    {"ticker": "AAL", "name": "American Airlines", "market": "US"},
    {"ticker": "LUV", "name": "Southwest Airlines", "market": "US"},
    {"ticker": "ALK", "name": "Alaska Air Group", "market": "US"},
    {"ticker": "FDX", "name": "FedEx", "market": "US"},
    {"ticker": "CSX", "name": "CSX Corp", "market": "US"},
    {"ticker": "NSC", "name": "Norfolk Southern", "market": "US"},
    {"ticker": "UNP", "name": "Union Pacific", "market": "US"},
    {"ticker": "CP", "name": "Canadian Pacific Kansas City", "market": "US"},
    {"ticker": "CNI", "name": "Canadian National Railway", "market": "US"},
    {"ticker": "EXPD", "name": "Expeditors International", "market": "US"},
    {"ticker": "GXO", "name": "GXO Logistics", "market": "US"},
    {"ticker": "RXO", "name": "RXO Inc", "market": "US"},
    # ── 농업/식품 인프라 ──
    {"ticker": "ADM", "name": "Archer-Daniels-Midland", "market": "US"},
    {"ticker": "BG", "name": "Bunge Global", "market": "US"},
    {"ticker": "FMC", "name": "FMC Corp", "market": "US"},
    {"ticker": "CTVA", "name": "Corteva", "market": "US"},
    # ── 추가 기술/핀테크 ──
    {"ticker": "SQ", "name": "Block Inc", "market": "US"},
    {"ticker": "AFRM", "name": "Affirm Holdings", "market": "US"},
    {"ticker": "SOFI", "name": "SoFi Technologies", "market": "US"},
    {"ticker": "COIN", "name": "Coinbase Global", "market": "US"},
    {"ticker": "SMAR", "name": "Smartsheet", "market": "US"},
    {"ticker": "ZI", "name": "ZoomInfo Technologies", "market": "US"},
    {"ticker": "BILL", "name": "Bill.com", "market": "US"},
    {"ticker": "PCTY", "name": "Paylocity", "market": "US"},
    {"ticker": "PAYC", "name": "Paycom Software", "market": "US"},
    {"ticker": "CSGP", "name": "CoStar Group", "market": "US"},
    # ── 추가 헬스케어/바이오 ──
    {"ticker": "UTHR", "name": "United Therapeutics", "market": "US"},
    {"ticker": "HZNP", "name": "Horizon Therapeutics", "market": "US"},
    {"ticker": "IONS", "name": "Ionis Pharmaceuticals", "market": "US"},
    {"ticker": "PRGO", "name": "Perrigo", "market": "US"},
    {"ticker": "JAZZ", "name": "Jazz Pharmaceuticals", "market": "US"},
    {"ticker": "INCY", "name": "Incyte Corp", "market": "US"},
    {"ticker": "EXEL", "name": "Exelixis", "market": "US"},
    {"ticker": "TECH", "name": "Bio-Techne", "market": "US"},
    {"ticker": "NEOG", "name": "Neogen Corp", "market": "US"},
    {"ticker": "TFX", "name": "Teleflex", "market": "US"},
    {"ticker": "HSIC", "name": "Henry Schein", "market": "US"},
    {"ticker": "COO", "name": "Cooper Companies", "market": "US"},
    {"ticker": "STE", "name": "Steris", "market": "US"},
    {"ticker": "GKOS", "name": "Glaukos Corp", "market": "US"},
    # ── 추가 금융/자산운용 ──
    {"ticker": "IVZ", "name": "Invesco", "market": "US"},
    {"ticker": "TROW", "name": "T. Rowe Price", "market": "US"},
    {"ticker": "BEN", "name": "Franklin Resources", "market": "US"},
    {"ticker": "AMG", "name": "Affiliated Managers Group", "market": "US"},
    {"ticker": "LPLA", "name": "LPL Financial", "market": "US"},
    {"ticker": "RJF", "name": "Raymond James Financial", "market": "US"},
    {"ticker": "SF", "name": "Stifel Financial", "market": "US"},
    {"ticker": "SEIC", "name": "SEI Investments", "market": "US"},
    {"ticker": "VRSK", "name": "Verisk Analytics", "market": "US"},
    {"ticker": "FDS", "name": "FactSet Research", "market": "US"},
    # ── 추가 소비재/레저 ──
    {"ticker": "POOL", "name": "Pool Corp", "market": "US"},
    {"ticker": "WHR", "name": "Whirlpool", "market": "US"},
    {"ticker": "LEG", "name": "Leggett & Platt", "market": "US"},
    {"ticker": "NVR", "name": "NVR Inc", "market": "US"},
    {"ticker": "PHM", "name": "PulteGroup", "market": "US"},
    {"ticker": "DHI", "name": "D.R. Horton", "market": "US"},
    {"ticker": "LEN", "name": "Lennar Corp", "market": "US"},
    {"ticker": "TOL", "name": "Toll Brothers", "market": "US"},
    {"ticker": "MDC", "name": "MDC Holdings", "market": "US"},
    {"ticker": "TMHC", "name": "Taylor Morrison Home", "market": "US"},
    # ── 추가 산업재/건설 ──
    {"ticker": "VMC", "name": "Vulcan Materials", "market": "US"},
    {"ticker": "MLM", "name": "Martin Marietta Materials", "market": "US"},
    {"ticker": "EXP", "name": "Eagle Materials", "market": "US"},
    {"ticker": "SUM", "name": "Summit Materials", "market": "US"},
    {"ticker": "STRL", "name": "Sterling Infrastructure", "market": "US"},
    {"ticker": "DY", "name": "Dycom Industries", "market": "US"},
    {"ticker": "ACM", "name": "AECOM", "market": "US"},
    {"ticker": "J", "name": "Jacobs Solutions", "market": "US"},
    {"ticker": "TTEK", "name": "Tetra Tech", "market": "US"},
    {"ticker": "KBR", "name": "KBR Inc", "market": "US"},
    # ── 추가 에너지/유틸리티 ──
    {"ticker": "OKE", "name": "ONEOK", "market": "US"},
    {"ticker": "WMB", "name": "Williams Companies", "market": "US"},
    {"ticker": "KMI", "name": "Kinder Morgan", "market": "US"},
    {"ticker": "EPD", "name": "Enterprise Products Partners", "market": "US"},
    {"ticker": "MMP", "name": "Magellan Midstream", "market": "US"},
    {"ticker": "TRGP", "name": "Targa Resources", "market": "US"},
    {"ticker": "AM", "name": "Antero Midstream", "market": "US"},
    # ── 추가 특수/다각화 ──
    {"ticker": "BR", "name": "Broadridge Financial", "market": "US"},
    {"ticker": "JKHY", "name": "Jack Henry & Associates", "market": "US"},
    {"ticker": "FIS", "name": "Fidelity National Info Services", "market": "US"},
    {"ticker": "FISV", "name": "Fiserv", "market": "US"},
    {"ticker": "GPN", "name": "Global Payments", "market": "US"},
    {"ticker": "WEX", "name": "WEX Inc", "market": "US"},
    {"ticker": "PRFT", "name": "Perficient", "market": "US"},
    {"ticker": "MANH", "name": "Manhattan Associates", "market": "US"},
    {"ticker": "CBRE", "name": "CBRE Group", "market": "US"},
    {"ticker": "JLL", "name": "Jones Lang LaSalle", "market": "US"},
    {"ticker": "CG", "name": "Carlyle Group", "market": "US"},
    {"ticker": "KKR", "name": "KKR & Co", "market": "US"},
    {"ticker": "APO", "name": "Apollo Global Management", "market": "US"},
    {"ticker": "BX", "name": "Blackstone", "market": "US"},
    {"ticker": "ARES", "name": "Ares Management", "market": "US"},
    {"ticker": "BAH", "name": "Booz Allen Hamilton", "market": "US"},
    {"ticker": "LDOS", "name": "Leidos", "market": "US"},
]
